# Generated by Django 2.2.5 on 2019-09-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_account_token',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
