# Generated by Django 2.2.5 on 2019-09-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190925_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_account_token',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
