# Generated by Django 2.2.5 on 2019-09-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190919_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
